### ISSUE TITLE
Open .TLF file from command-line or shortcut

### ISSUE THREAD

**Issue by Gargantubrain** [cshnik/TaskLayout#4]
Can not seem to open a .TLF file without having to manually right-click the tray icon > Open Layout > blahblah.TLF

Please add a way to open a .TLF file from command-line so that we can re-arrange windows easily from our choice of desktop icon, windows hotkey, launcher, etc. Thank you!

We should be able to accomplish this by executing something like:
TaskLayout64.exe blahblah.TLF 
TaskLayout64.exe -openlayout blahblah.TLF

**Comment by Gargantubrain** [comment]
I just noticed if I close the tray icon as in right-click, Exit, then open a TLF file then it will run it. Once. Then the tray icon stays running, so it has to be closed again. I can certainly work around this with a batch file such as taskkill -im "tasklayout64.exe" , pause, then open the TLF again, but please do add the ability to do this properly so it doesn't have to be worked around as a hack. Thanks!

**Comment by cshnik** [comment]
The issue was fixed in the version 0.6.0.1.
Feel free to download it [here](http://www.systemgoods.com).
